runtime: python27
api_version: 1
threadsafe: true

handlers:
  - url: /
    static_files: dist/angularfrontend/index.html
    upload: dist/angularfrontend/index.html

  - url: /
    static_dir: dist/angularfrontend
